# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'RepositoriosSwiftAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'PromiseKit'

  # Pods for RepositoriosSwiftAPI

  target 'RepositoriosSwiftAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
